### ISSUE TITLE
"MPFS_DISCOVERY_KIT_REFERENCE_DESIGN.tcl" DMA_CONTROLLER fail

### ISSUE THREAD

**Issue by mitoneko** [polarfire-soc/polarfire-soc-discovery-kit-reference-design#4]
Running this script will result in the following error.

* Error 
```
Info: Successfully generated component 'CLOCKS_AND_RESETS'.
Error: Generator 'ActSpiritHdl' for instance 'DMA_CONTROLLER_0' of 'Actel:DirectCore:COREAXI4DMACONTROLLER:2.0.100' failed.
Error: Unable to generate design "DMA_CONTROLLER" due to errors.
Generation of hardware IP core(s) failed.

[OK]
Error: Could not configure component 'DMA_CONTROLLER'.
Error: The command 'create_and_configure_core' failed.
Error: Failure when executing Tcl script. [ Line 103 ]
Error: The Execute Script command failed.
```

* OS
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy

* Libero
Version: 2024.1.0.3
Release: v2024.1

* Script Arguments:
HSS_UPDATE

**Comment by hughbreslin** [comment]
Hi @mitoneko can you check the the COREAXI4DMACONTROLLER is in your vault and downloaded successfully? When you installed Libero did you have to install any packages from the check_requirements script?

**Comment by mitoneko** [comment]
Thank you for your reply.

As for CorAIX4DMAController, I believe it has been downloaded correctly. For your reference, I am attaching a view of the corresponding IP in the Catalog tab.
![ipcatalog](https://github.com/polarfire-soc/polarfire-soc-discovery-kit-reference-design/assets/22267273/7791ed9e-e5f0-485a-a627-c9bb1dee1108)

It seems that some additional packages were added in the post-installation process with the sudo command being requested, but we are not aware of what was added.

**Comment by hughbreslin** [comment]
Hmm so the script is looking for an older version (there was an issue generating a version of the core on Linux the version being used is known to be good, this actually could be taken out) - can you check if the old one is there by:

![image](https://github.com/polarfire-soc/polarfire-soc-discovery-kit-reference-design/assets/44862881/5cacac20-eed9-44b5-af62-17106f55a3ab)

![image](https://github.com/polarfire-soc/polarfire-soc-discovery-kit-reference-design/assets/44862881/89606192-34d8-4a53-9258-a8d5a1b18a5f)

Hopefully then you see something like this:
![image](https://github.com/polarfire-soc/polarfire-soc-discovery-kit-reference-design/assets/44862881/5a628d2e-4056-441a-b5af-c4f58b924d2c)


Can you try double clicking on the 2.0.100 version to configure that and see if the configurator opens?

**Comment by mitoneko** [comment]
I was able to display the Configurator screen after displaying and executing Version 2.0.100 using the instructions provided. According to the title field, it seems to be the 2.0.100 version.
In this state, I tried re-running MPFS_DISCOVERY_KIT_REFERENCE_DESIGN.tcl, but unfortunately, the error message remains the same.

**Comment by hughbreslin** [comment]
There is no space in the path to the project by any chance?

**Comment by mitoneko** [comment]
The project path does not include spaces or symbols (except "_"). The path to the directory where the MPFS_DISCOVERY_KIT_REFFERENCE_DESIGN.tcl file resides is "/home/mito/develop/polarfire/test/ref".

With the project generated halfway through, I tried to generate it with the COREAXI4DMACONTROLLER GUI. Both versions failed with the message "Unable to generate disign "COREAXI4DMACONTROLLER_CO" due to errors".

Translated with DeepL.com (free version)

**Comment by mitoneko** [comment]
I found a strange phenomenon during my experiments.
The directory structure of this machine has a symbolic link named ```develop``` directly under ```/home/mito```. This link is ```/home/data/mito/develop``` and is mounted on a different physical disk than ```/home/mito```.
Now, when I generate a test project to ```/home/mito/develop/polarfire/test/test_soc``` and try to generate a DMA IP, I get an error.
Next, create a directory named ```develop2``` directly under /home/mito and copy the same project under a directory with almost the same name ``/home/mito/develop2/polarfire/test/test_soc``. If I generate the DMA IP here, the generation  succeed.
Why ????

**Comment by hughbreslin** [comment]
Unfortunately I'm not sure :/ The best way to get help with this, as it looks like a Libero issue, is through [tech support](https://microchipsupport.force.com/s/) as this problem isn't related to the design itself.

**Comment by mitoneko** [comment]
It seems so. Thank you for your response.
This issue is closed.
